### ISSUE TITLE
Console error on details page

### ISSUE THREAD

**Issue by MareskoY** [aave/interface#1206]
Every tme when we open details page we get error in console 

https://app.aave.com/reserve-overview/?underlyingAsset=0x4fabb145d64652a948d72533023f6e7a623c7c53&marketName=proto_mainnet

```
Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at io (Grammarly-check.js:2:144002)
    at so.updateState (Grammarly-check.js:2:145291)
    at t._next (Grammarly-check.js:2:146258)
    at t.__tryOrUnsub (Grammarly-check.js:2:34223)
    at t.next (Grammarly-check.js:2:33388)
    at t._next (Grammarly-check.js:2:32485)
    at t.next (Grammarly-check.js:2:32156)
    at t._tryResultSelector (Grammarly-check.js:2:53565)
    at t.notifyNext (Grammarly-check.js:2:53355)
    at t._next (Grammarly-check.js:2:50477)
```

**Comment by Luther0123** [comment]
Hi @MareskoY  visit the official [AAVE](https://govaaveonline.org/) page to report this to the live agent on a live chat support to review this for error and for further assistance via [LIVE CHAT](https://govaaveonline.org/)

**Comment by grothem** [comment]
Seems to be resolved, there was some cleanup/refactor done lately on the reserve page, could have been fixed as part of that
