### ISSUE TITLE
cannot borrow asset when it is available

### ISSUE THREAD

**Issue by marinushap** [aave/interface#1355]
**Describe the bug**
cannot borrow assets 
**To Reproduce**

1. Go to https://app.aave.com/?marketName=proto_optimism_v3
2. Click on borrow
3. opens a windiw with borrow asset
4. input available amount
5. approve it in the wallet with gaz approvment

**Expected behavior**
the asset shoud be borrowed, but instead i get a message that "Transaction failed
You can report incident to our [Discord](https://discord.gg/7kHKnkDEUf) or [Github](https://github.com/aave/interface)."

**Screenshots**

**Desktop (please complete the following information):**

- OS: windows 10
- Browser chrome
- Version 108.0.5359.98
- 

**Additional context**

```txt
insufficient funds for intrinsic transaction cost (error={"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"invalid transaction: insufficient funds for gas * price + value\"}}}'","stack":"{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"invalid transaction: insufficient funds for gas * price + value\\\"}}}'\",\n  \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"invalid transaction: insufficient funds for gas * price + value\\\"}}}'\\n    at new f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308766)\\n    at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311522)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312132)\\n    at m.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:182464)\\n    at Object.l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:10:210880)\\n    at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:3:1144)\\n    at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:3:1680)\\n    at m._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:228939)\\n    at m.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:228163)\\n    at L._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:210630)\\n    at L.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:194318)\\n    at async L.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:193528)\\n    at async s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:10:58943)\"\n}\n  at new f (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:308766)\n  at i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:311522)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-2.js:1:312132)\n  at m.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:182464)\n  at Object.l (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:10:210880)\n  at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:3:1144)\n  at s.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-7.js:3:1680)\n  at m._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:228939)\n  at m.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:228163)\n  at L._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:210630)\n  at L.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:194318)\n  at async L.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:193528)\n  at async s.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:10:58943)"}, method="sendTransaction", transaction=undefined, code=INSUFFICIENT_FUNDS, version=providers/5.5.3)
```

**Comment by grothem** [comment]
Closing this from inactivity
